
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by CSGenerator.
// </auto-generated>
//------------------------------------------------------------------------------
using SharpKit.JavaScript;

[assembly: JsExport(Minify = false, DefaultFilename = "Assets/JavaScript/GameLogicCode.bytes")]

#region JsType
[assembly: JsType(TargetTypeName = "GameSocketInterface", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Network.MessageParent", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Network.MessageWrap", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Network.ProtoBufferWrap", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Protobuf.UserProto", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TestNetWork", Mode = JsMode.Clr)]

#endregion